### ISSUE TITLE
Django 1.8.x and django-nose => creation

### ISSUE THREAD

**Issue by josemariaruiz** [django-nose/django-nose#186]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 87, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django_nose/__init__.py", line 4, in <module>
    from django_nose.runner import *
  File "/home/josemaria/earlybird/venv/local/lib/python2.7/site-packages/django_nose/runner.py", line 23, in <module>
    from django.db.backends.creation import BaseDatabaseCreation
ImportError: No module named creation

```

**Comment by hwkns** [comment]
Fixed in https://github.com/django-nose/django-nose/commit/ae2c1bbe851131adbec773fe1bebbd03d9be2bd2

**Comment by peterbe** [comment]
Let's close this then.

**Comment by DebauchedSloth** [comment]
Any idea when a release with those fixes in it might happen?  I'd like to start playing with django 1.8 and I'd rather not install nose from git.

**Comment by hwkns** [comment]
@DebauchedSloth there is still at least one outstanding issue with Django 1.8: https://github.com/django-nose/django-nose/issues/178

**Comment by glynjackson** [comment]
Has this been fixed? 

Running latest version from pip 1.3 and I still get this error running Django 1.8....

```
    app_config = AppConfig.create(entry)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django_nose/__init__.py", line 4, in <module>
    from django_nose.runner import *
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django_nose/runner.py", line 23, in <module>
    from django.db.backends.creation import BaseDatabaseCreation
```

Thanks

**Comment by glynjackson** [comment]
Also if I use the master branch version I get the error:

```
(env)Glyns-MacBook-Pro:ctzn-api glyn$ python manage.py test
/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django_nose/runner.py:24: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 327, in create_parser
    parser.add_option(opt)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -v/--verbose: conflicting option string(s): -v
(env)Glyns-MacBook-Pro:ctzn-api glyn$ python manage.py test
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 378, in run_from_argv
    parser = self.create_parser(argv[0], argv[1])
  File "/Users/glyn/Documents/workspace/ctzn-api/env/lib/python2.7/site-packages/django/core/management/base.py", line 327, in create_parser
    parser.add_option(opt)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1021, in add_option
    self._check_conflict(option)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 996, in _check_conflict
    option)
optparse.OptionConflictError: option -v/--verbose: conflicting option string(s): -v
```

**Comment by hwkns** [comment]
@glynjackson see https://github.com/django-nose/django-nose/issues/178

**Comment by glynjackson** [comment]
@hwkns Sorry, yes spotted this just after I posted, thanks. Does anyone have any updates on these issues? Django 1.8 is out and I cannot run tests anymore without any nasty hacks. PS. django-nose is an amazing package and I appreciate the efforts!

**Comment by josemariaruiz** [comment]
+1 

Just migrated to Django 1.8... and had to go back to the standard test runner :cry:

**Comment by jwhitlock** [comment]
1.4 will be released shortly, will include this fix
